import "@/styles/main.scss";

import { CartProvider } from "@/context";
import { Header, Footer } from "@/components";

export const metadata = {
    title: "Floom Flowers & Gifts",
    description: "Generated by create next app",
    icons: {
        icon: "https://d34g78fsj6jubz.cloudfront.net/images/favicon-svg.svg",
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <CartProvider>
                    <Header />
                    {children}
                    <Footer />
                </CartProvider>
            </body>
        </html>
    );
}
